os:
- linux
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: danwos
  password:
    secure: no_hash_yet
  on:
    tags: true
    branch: master
