os:
- linux
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install six
- pip install --upgrade pip setuptools
- pip install tox-travis
install:
- python setup.py install
script: tox
deploy:
  provider: pypi
  user: danwos
  password:
    secure: "Zt9ZBsXgASdbj4M1pAP535QqVopunaLSl+/oSESHVNqo1FOpizARodH+HCHLaW4AP4mpn3w3lkKghyDi9meKwQGLi1pks7V4QkZ/JvHiPiXwWBu8r8bJLVlBibK0uBUQdkjnT6JnqoHKVsAeYs1rp+Y5FGqp6YW8536naRicwcfq+tDhtm/mQM/cAVkL5baelGAzs7t4xwZQvxGQVSJeAzcQSSfF8eSyNAdfz1VPkwQc/v5Ugp/3utM2jr7tqX0D6h0ozmrxa7GMWn88BF0MWMHCYbutYbDCgXv0MeO80/3+1JZMwsIyvZDFdi05NlySswBfdTBFOUScnUKHWr93sETcqbB3YbAPautFLd4z0ej6Qj0/zDDo9fEcVuvlRguyTF88UIk7ENJjsdQKmbDsHyxvu+H5j6YMt2MtB7aqu0gJzTK7kQL5bpfyDUaUOIGIwoSaFgWyK8hb9yiq6g1ak0Uw50qnIWPgZaMvsofll+wCSbjgGYH0BngwAePfbRBscQgexn3dkNy5quMhOBa3tJZUbplp9t94y3SML4xC/HwbuWousZMoxYQU5yRP258ovO0Fii60YIyzfovxF+xb5Xyw2GZ1Bv0HaWMdIjzfpAggdYO0Q51/gYXR0BmoM5xxoKhQiqi6iyadK830CgkYKB2rI/l2ijtOVlG9Fko31CI="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: useblocks/groundwork-users
